application: facebook-openid
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /(robots.txt|favicon.ico)
  static_files: static/\1
  upload: static/(robots.txt|favicon.ico)
  secure: optional

- url: /facebook.*
  script: facebookoauth.py

- url: .*
  script: provider.py
